print(f"cast number into string: {str(10)}")
print(f'uppercase "hello world": {"hello world".upper()}')
print(f'lowercase "Hello World": {"Hello World".lower()}')
print(f'Join: {",".join("12345")}')
print(f'is numeric: {"12345".isnumeric()}')
print(f'is alpha: {"12345".isalpha()}')
print(f'is alphanumeric: {"12345abc".isalnum()}')
print(f'trim "Hello World    ": {"Hello World    ".strip()}|')
print(f'replace: {"Hello Vorld".replace("V", "W")}')
print(f'split "Hello World": {"Hello World".split()}')
lines = "Hello World\nHow are you?\nI am Fine"
print(f'splitlines "Hello World\\nHow are you?\\nI am Fine": {lines.splitlines()}')
print(f'title "my title": {"my title".title()}')
print(f'swapcase "Hello World": {"Hello World".swapcase()}')
print(f'Find "a" in attack: {"attack".find("a")}')
print(f'Find "World" in Hello World: {"Hello World".find("World")}')
print(f'Index of "a" in attack: {"attack".index("a")}')
print(f'last index of "a" in attack: {"attack".rfind("a")}')
print("Hello {}".format("World"))
print(f'is "Hello World startsWith Hello: {"Hello World".startswith("Hello")}')
print(f'is "Hello World endsWith World: {"Hello World".endswith("World")}')

table = "xyllo World".maketrans("xy", "He")
print(f'Translate "xyllo World": {"xyllo World".translate(table)}')
